{"is_success": "Fail", "type": "road_dog_extract", "bgnde": "20221019", "params": {"serviceKey": "Trk0PUjGXkzmL99c4tVFWTwqQcElfON82T+zMvqwy1gy6G+TOz0Y1LWagIbe5xjXtWsSMXVhO92jGIsFoxChXA==", "bgnde": "20221019", "endde": "20221019", "upkind": "417000", "_type": "json", "numOfRows": "1000"}, "err_msg": "HTTPConnectionPool(host='apis.data.go.kr', port=80): Max retries exceeded with url: /1543061/abandonmentPublicSrvc/abandonmentPublic?serviceKey=Trk0PUjGXkzmL99c4tVFWTwqQcElfON82T%2BzMvqwy1gy6G%2BTOz0Y1LWagIbe5xjXtWsSMXVhO92jGIsFoxChXA%3D%3D&bgnde=20221019&endde=20221019&upkind=417000&_type=json&numOfRows=1000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13cd01f490>: Failed to establish a new connection: [Errno 111] Connection refused'))"}
